
import { Product, Benefit, Review } from './types';

export const BUSINESS_NAME = 'Prakriti Greens';
export const WHATSAPP_NUMBER = '919096522819';
export const DISPLAY_PHONE = '+91 90965 22819';

export const PRODUCTS: Product[] = [
  // ── 1. LIVING & FRESH-CUT MICROGREENS (CORE PILLAR 1) ───────────
  {
    id: 'mg1',
    name: 'Royal Sango Radish Microgreens',
    description: 'Breathtaking deep purple living canopy with an appetizing peppery crunch. Packed with anthocyanins and up to 40× concentrated vitamin levels.',
    price: 350,
    image: '/Radish.png',
    type: 'live-tray',
    category: 'microgreens',
    containerType: 'Living Hydroponic Tray (Bio-Degradable)',
    weight: '1 Living Tray (15-20 Servings)',
    prepTime: 'Snip & Eat • Zero Waste',
    benefits: ['Natural Detox', 'Instant Energy', 'Skin Glow'],
    badge: 'Signature Live Tray',
    emoji: '🌱',
    inStock: true,
  },
  {
    id: 'mg2',
    name: 'Sweet Tendril Pea Shoots',
    description: 'Crisp, sweet, tender pea shoots harvested minutes prior to sealing in moisture-lock eco-containers. Perfect for salads and hot pan tossing.',
    price: 180,
    image: '/Pea.png',
    type: 'fresh-cut',
    category: 'microgreens',
    containerType: 'Airtight Fresh-Cut Deli Pack',
    weight: '150g Sealed Container',
    prepTime: 'Rinse-Free • Ready to Plate',
    benefits: ['High Plant Protein', 'Folate Source', 'Low Glycemic'],
    badge: 'Customer Favorite',
    emoji: '🌿',
    inStock: true,
  },
  {
    id: 'mg3',
    name: 'Broccoli Sprouts & Microgreens',
    description: 'The world-renowned sulforaphane powerhouse. Grown in pure mineral water under precision climate control for maximum enzyme vitality.',
    price: 400,
    image: '/Broccoli.png',
    type: 'live-tray',
    category: 'microgreens',
    containerType: 'Living Hydroponic Tray',
    weight: '1 Living Tray (Keep Growing)',
    prepTime: 'Harvest Seconds Before Eating',
    benefits: ['Cell Regeneration', 'Sulforaphane Rich', 'Immune Shield'],
    badge: 'Top Therapeutic',
    emoji: '🥦',
    inStock: true,
  },
  {
    id: 'mg4',
    name: 'Golden Sunflower Greens',
    description: 'Substantial, juicy, and deliciously nutty microgreen stems. Dense in healthy plant fats, Vitamin E, and essential trace minerals.',
    price: 200,
    image: '/Sunflower.png',
    type: 'fresh-cut',
    category: 'microgreens',
    containerType: 'Airtight Fresh-Cut Deli Pack',
    weight: '180g Sealed Container',
    prepTime: 'Ready to Toss in Salads',
    benefits: ['Zinc Loaded', 'Cardio Health', 'Muscle Vitality'],
    badge: 'Salad Essential',
    emoji: '🌻',
    inStock: true,
  },

  // ── 2. FRESH CUT VEGETABLES IN PACKED CONTAINERS (CORE PILLAR 2) ──
  {
    id: 'cv1',
    name: 'Gourmet Stir-Fry Veggie Mix',
    description: 'Farm-fresh bell peppers, broccoli florets, tender baby corn, sliced carrots, and zucchini. Pre-washed with ozone purification, precision diced, and packed in an airtight food-grade seal.',
    price: 240,
    image: '/cut_veggies_pack.jpg',
    type: 'packed-container',
    category: 'cut-vegetables',
    containerType: 'Airtight Food-Grade Lock Container',
    weight: '550g Sealed Tub (Serves 2-3)',
    prepTime: 'Pre-Washed & Diced • Ready to Pan',
    benefits: ['Zero Prep Time', 'Ozone Sanitized', 'High Dietary Fiber'],
    badge: 'Bestselling Prep',
    emoji: '🍱',
    inStock: true,
  },
  {
    id: 'cv2',
    name: 'Microgreen Harvest Salad Bowl',
    description: 'Hand-cut baby spinach, crisp red cabbage, sliced European cucumbers, and cherry tomatoes, crowned with live radish & pea microgreens with an artisan lemon tahini dressing cup.',
    price: 220,
    image: '/salad_microgreen_pack.jpg',
    type: 'packed-container',
    category: 'cut-vegetables',
    containerType: 'Sealed Clear Deli Salad Bowl with Cup',
    weight: '380g Bowl (Single/Shareable)',
    prepTime: 'Pour Dressing & Toss • Instant Meal',
    benefits: ['Microgreen Infused', 'Enzyme Active', 'Low Calorie Crunch'],
    badge: 'Ready to Eat',
    emoji: '🥗',
    inStock: true,
  },
  {
    id: 'cv3',
    name: 'Traditional Stew & Curry Veg Prep',
    description: 'Neatly cubed butternut squash/pumpkin, hand-snapped French beans, peeled country shallots, diced carrots, fresh curry leaves & cilantro in a 4-compartment sealed container.',
    price: 195,
    image: '/curry_cut_veggies.jpg',
    type: 'packed-container',
    category: 'cut-vegetables',
    containerType: '4-Compartment Airtight Prep Container',
    weight: '450g Packed Tray (Serves 3-4)',
    prepTime: 'Zero Peeling • Directly into Pot',
    benefits: ['Ayurvedic Blend', 'Zero Food Waste', '100% Pesticide-Free'],
    badge: 'Homestyle Comfort',
    emoji: '🍲',
    inStock: true,
  },

  // ── 3. READY TO COOK CONTAINER KITS (CORE PILLAR 3) ───────────────
  {
    id: 'rtc1',
    name: 'Paneer & Veggie Stir-Fry Chef Kit',
    description: 'Complete 10-minute dinner box: fresh soft organic paneer cubes, diced tri-color bell peppers, snap peas, baby corn, mushrooms, a sealed savory ginger-soy sauce cup, and live microgreen garnish.',
    price: 320,
    image: '/ready_to_cook_container.jpg',
    type: 'ready-to-cook-kit',
    category: 'ready-to-cook',
    containerType: 'Chef-Divided Sealed Meal Prep Kit',
    weight: '600g Complete Kit (Serves 2)',
    prepTime: 'Cook in 8-10 Minutes • One Skillet',
    benefits: ['High Protein (32g)', 'Restaurant Quality', 'Microgreen Garnish'],
    badge: 'Chef Favorite',
    emoji: '🍳',
    inStock: true,
  },
  {
    id: 'rtc2',
    name: 'Thai Green Curry Ready Kit',
    description: 'Pre-portioned bamboo shoots, baby eggplants, broccoli florets, sweet basil, authentic fresh ground green curry paste, and pea microgreens for an aromatic coconut broth.',
    price: 340,
    image: '/cut_veggies_pack.jpg',
    type: 'ready-to-cook-kit',
    category: 'ready-to-cook',
    containerType: 'Divided Sealed Curry Prep Container',
    weight: '520g Box (Serves 2-3)',
    prepTime: 'Simmer 12 Mins • Just Add Coconut Milk',
    benefits: ['Exotic Flavors', 'Ozone Cleaned', 'Zero Preservatives'],
    badge: 'Weekend Special',
    emoji: '🍛',
    inStock: true,
  },

  // ── 4. SEASONAL HARVEST (PRESERVED CORE DETAILS) ──────────────────
  {
    id: 'fr2',
    name: 'Indian Blackberry (Jambhul)',
    description: 'Monsoon jewel from Maharashtra orchards. Wild-harvested, low glycemic index, dense with anthocyanins and natural iron.',
    price: 299,
    image: '/jambhul_3d.png',
    type: 'fruit',
    category: 'fruits',
    containerType: 'Ventilated Eco Carton (1 kg)',
    weight: '1 kg Harvest Box',
    prepTime: 'Ready to Wash & Savor',
    benefits: ['Blood Sugar Support', 'Iron Rich', 'Monsoon Antioxidants'],
    badge: 'Monsoon Harvest',
    emoji: '🫐',
    inStock: true,
  },
  {
    id: 'fr1',
    name: 'Ratnagiri Alphonso Mango',
    description: 'Authentic GI-tagged Ratnagiri mangoes. Sun-ripened on straw beds with zero carbide. Buttery, fibre-free sweetness.',
    price: 499,
    image: '/mango_3d.png',
    type: 'fruit',
    category: 'fruits',
    containerType: 'Padded Wooden/Carton Crate',
    weight: '1 Dozen (12 pcs)',
    prepTime: 'Chilled & Sliced',
    benefits: ['Vitamin C Rich', 'Natural Enzymes', 'GI-Certified'],
    badge: 'Summer Restock Soon',
    emoji: '🥭',
    inStock: false,
  },
];


export const BENEFITS: Benefit[] = [
  {
    title: '40× Scientific Potency',
    description: 'Our living microgreens are laboratory tested to contain up to 40× the nutrient and antioxidant density of mature plants. Maximum vitality in every crunch.',
    icon: 'fa-solid fa-microscope',
  },
  {
    title: 'Airtight Sealed Containers',
    description: 'Fresh cut vegetables and ready-to-cook kits are triple-washed, ozone sanitized, and sealed in airtight food-grade tubs to lock in peak moisture & nutrients for 5+ days.',
    icon: 'fa-solid fa-box-archive',
  },
  {
    title: 'Living Trays in Your Kitchen',
    description: 'Living Trays arrive actively growing with roots intact. Harvest seconds before consumption for zero enzyme decay and ultimate farm freshness.',
    icon: 'fa-solid fa-seedling',
  },
  {
    title: 'Zero Prep, 10-Min Cooking',
    description: 'No peeling, no chopping, zero food waste. Open the sealed container, toss straight into the pan or pot, and enjoy gourmet farm meals in minutes.',
    icon: 'fa-solid fa-clock',
  },
];

export const INSTAGRAM_REVIEWS: Review[] = [
  {
    name: 'Dr. Ananya Joshi',
    handle: '@ananya_lifestyle',
    text: 'The ready-to-cook paneer & veggie kit in the sealed container is a game changer for busy clinic days! Zero chopping, fresh microgreens on top, done in 8 minutes. 🍱',
    rating: 5,
  },
  {
    name: 'Priya Sharma',
    handle: '@priya_wellness',
    text: 'These microgreens changed my morning routine. The Royal Sango radish variety is peppery, fresh, and stays alive on my kitchen counter! 🌱',
    rating: 5,
  },
  {
    name: 'Chef Kabir Deshmukh',
    handle: '@kabir_cooks',
    text: 'The gourmet stir-fry cut vegetable container arrived crisp, dry, and sealed airtight. The cut precision is chef-grade. Perfect crunch every time.',
    rating: 5,
  },
  {
    name: 'Sneha Patel',
    handle: '@snehaeats',
    text: 'The Alphonso mangoes and seasonal fruits are unreal! Impossibly sweet, juicy, and zero fibre. Prakriti Greens delivers farm purity every single time 🥭',
    rating: 5,
  },
  {
    name: 'Rohan Kulkarni',
    handle: '@rohanfit',
    text: 'Broccoli sprouts and sunflower greens in the deli pack are insanely fresh. My salads and protein bowls have never tasted this vibrant.',
    rating: 5,
  },
  {
    name: 'Arjun Mehta',
    handle: '@arjun_health',
    text: 'The traditional stew & curry pre-cut container saved me 30 minutes of prep today. Sambar was ready in a flash with zero vegetable waste. So practical!',
    rating: 5,
  },
];

